### ISSUE TITLE
About naming files when decrypting/exporting (Texture)

### ISSUE THREAD

**Issue by CharlieFuu69** [nosyrbllewe/LLASDecryptor#12]
Hello!
A while ago I noticed that, in particular, the files in the `texture` table, when decrypted, are renamed in a way that makes it difficult for me to classify, especially the cards.

After reading the databases, I realized that the files are renamed as:
```
[Package Name]_[Head]
```
To organize the cards, I have literally had to go through them one by one, because the file names just don't help me.

In audio files, for example, in voices, I can organize them well because they have the School Idol identifier, such as:
```
mXXYY

XX = Unit Number
YY = Character Number
```
And the reference to the characters with that format is as follows:

| Character number | μ's (00) | Aqours (01) | Nijigasaki HS (02) |
|---|---|---|---|
| 01               | Honoka   | Chika       | Ayumu              |
| 02               | Eli      | Riko        | Kasumi             |
| 03               | Kotori   | Kanan       | Shizuku            |
| 04               | Umi      | Dia         | Karin              |
| 05               | Rin      | You         | Ai                 |
| 06               | Maki     | Yoshiko     | Kanata             |
| 07               | Nozomi   | Hanamaru    | Setsuna            |
| 08               | Hanayo   | Mari        | Emma               |
| 09               | Nico     | Ruby        | Rina               |
| 10               |          |             | Shioriko           |
| 11               |          |             | Mia                |
| 12               |          |             | Lanzhu             |

Is there any chance that, in a future update, the naming of the Texture files will change?
That would help me a lot.

PS: I was reading almost all the tables in the databases, and I couldn't find any significant pattern that alludes to the head.

**Comment by nosyrbllewe** [comment]
The head is the byte offset for the file package, such as ly4oob_760782 for the second row in the following example.
![image](https://github.com/nosyrbllewe/LLASDecryptor/assets/2175256/795ed8c8-3b1f-4789-9f80-d2cfb40fb1f6).

The audio files also originally followed the same `[Package Name]_[Head]` format, but I later wrote a converter to rename them for easier use.

I was actually intending on doing a similar converter for texture names a while ago, but lost interest in doing so after the game shut down. It was also much more complicated than naming for the audio files as there are a bunch more different types of texture files (and so looking up the correct name becomes significantly more complex). I am not sure if I will go back to it though.

**Comment by nosyrbllewe** [comment]
It was much easier for the audio files as they have a convenient name for each of the files next to it in the data. 
![image](https://github.com/nosyrbllewe/LLASDecryptor/assets/2175256/f971d1fb-78fe-4c84-a898-43f5b59c5d08)
Unfortunately,  the texture files do not.  The main problem is that I am unsure on how to map the following asset_paths to a unique and useful name:
![image](https://github.com/nosyrbllewe/LLASDecryptor/assets/2175256/4742ef25-c548-4d0f-a95b-5d29c99c223b)
I tried looking in the database tables, but I don't see any nice mapping for them.

**Comment by CharlieFuu69** [comment]
Yes, I actually saw those same databases, and what seemed to be a good indicator (`asset_path`), because for me it is still unintelligible, and I do not know its use.

I see that it is a problem that we have in common, but I also appreciate your effort to make this tool =D

PS: I have marked this Issue as closed.
